EngFlow/example

.bazelrc
remote_config/cc/BUILD
remote_config/cc/stub_cc_toolchain_config.bzl

- In .bazelrc:
- Add --cpu=k8. Without this, Bazel tries to select darwin_arm64 (or whatever
the native platform is). This is still needed because Bazel still doesn't
fully support platforms and toolchains for C++.
- Add comments explaining what's missing and what to change.
- Remove --tls_certificate. Bazel reports an error if it's used.
(Should engflow-ca.crt be removed, too?)
- In //remote_config/cc:
- Generalize armeabi_cc_toolchain_config to stub_cc_toolchain_config
and declare a stub for darwin_arm64. This shouldn't be needed in theory,
and C++ targets build without it, but Java targets need it. More stubs
may be needed for --cpu values on other platforms.
- Run buildifier on BUILD.

Support cross-compilation from macOS for C++ and Java in .bazelrc

---

java/com/engflow/notificationqueue/Client.java

The IOException was never reached. The build throws: warning catch never reached.

Removed IOException as it was never reached

---

java/com/engflow/example/BUILD

No wildcard, so no need for glob.

Remove globs from Java example

---

.github/workflows/main.yml

Because of https://github.com/EngFlow/example/issues/38

Changed macos runner from 10.15 (deprecated) to 11 (latest)

---

WORKSPACE
typescript/BUILD
typescript/main.ts
typescript/package.json
typescript/pnpm-lock.yaml
typescript/tsconfig.json

Adding Typescript support and hello world test. 
Run with `bazel test  //typescript:typesctript_test`
Progress https://github.com/EngFlow/example/issues/36

Added typescript support and hello world test

---

.bazelrc
.github/workflows/main.yml
WORKSPACE
csharp/BUILD
csharp/Main.cs

Adding csharp support and hello world example. 
Run with
**Linux**
```sh
bazel build --host_platform @io_bazel_rules_dotnet//dotnet/toolchain:linux_amd64_3.1.100 --platforms @io_bazel_rules_dotnet//dotnet/toolchain:linux_amd64_3.1.100 //csharp/...
```
**MacOS**
```sh
bazel build --host_platform @io_bazel_rules_dotnet//dotnet/toolchain:darwin_amd64_3.1.100 --platforms @io_bazel_rules_dotnet//dotnet/toolchain:darwin_amd64_3.1.100 //csharp/...
```
Progress https://github.com/EngFlow/example/issues/36

Added support for csharp and hello world example

---

WORKSPACE

Updated and mirrored:
- rules_proto_grpc
- io_bazel_rules_go
- aspect_rules_ts
- io_bazel_rules_dotnet
Remaining 
- rules_proto
- kotlin

Updated some more WORKSPACE dependencies

---

WORKSPACE

- Fetching emacs and ubuntu is slow. Having the files in https://storage.googleapis.com/engflow-tools-public is faster. 
- Three mirrored files were wrongly referenced.

Changing some url for mirrored files

---

WORKSPACE

I wanted to see if the most recent commit helped with the [notification queue client issue](https://github.com/EngFlow/example/issues/70). It did not help.

Upgrading engflowapis

---

.github/renovate.yml
.github/workflows/renovate.yml
renovate.json

The workflow only has `workflow_dispatch` but I plan to use the commented line as well for `schedule`. I am not adding a new secret in the repository as it is a security issue (anybody could use it). I am using normal `GITHUB_TOKEN` that should work given that the repo is piublic. Right now activating updates for `bazel` and `npm`.

Adding renovate workflow for automatic deps update

---

WORKSPACE

Using renovate to update the `WORKSPACE` creates one problem: our `URL` for mirrored `tar` and `zip` files.
Given that currently we do not have an automatic way for mirroring deps, then renovate only changes the github URL leaving our own mirrored URL untouched. This of course fails (`404`) for a changed version, making it always use the github URL. 
Lets add the URL's back when the mirroring procedure is complete: https://github.com/EngFlow/engflow/issues/12797

Removing all engflow-tools-public urls

---

.github/workflows/main.yml

- Executing bazel test only for `//java/com/engflow/example`
- The `notification queue` do not have tests as it is needed an `authentication` mechanism to run against clusters. We do not have such thing here because it is a public repo.
- We do have, and will implement more, tests in the java example directory. It runs remotely too.
- Changing the job name to testing for all directory that execute tests instead of builds. Note that we will add test for every language.
- Also, file formatting.

Small changes in main workflow

---

genrules/BUILD

- Unnecessary load to CI which runs on github hosts.
- This is better for CI when creating PR in this repository.
- Uncomment to test against Opal or any other cluster. 
Also [slack thread](https://engflow.slack.com/archives/C01CHBZ3U3U/p1678476731406569).

Do not run genrules (that depend on files) by default

---

.github/workflows/main.yml

The docs [1] seem to indicate that we can read secrets from `pull_request_target`, which we could use to get authentication tokens for RE.
[1] https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

[ci] Switch to `pull_request_target`

---

renovate.json

- Only two reviewers suffice (the two with more changes in the repo, except Ulf)
- Setting PR limit to 0: we will get all pr updates for all dependencies for `bazel` and `npm`.

[renovate bot] Small changes to renovate bot config

---

typescript/package.json
typescript/pnpm-lock.yaml

With the latest version we get this (locally and in github runners): 
```sh
ERROR: An error occurred during the fetch of repository 'npm_typescript':
Traceback (most recent call last):
File "/home/andres/.cache/bazel/_bazel_andres/3d5b4782dbb193b9df57e427c9279258/external/aspect_rules_ts/ts/private/npm_repositories.bzl", line 35, column 13, in _http_archive_version_impl
fail("""typescript version {} is not mirrored in rules_ts, is this a real version?
Error in fail: typescript version 5.0.2 is not mirrored in rules_ts, is this a real version?
```
I tried to revert this two days ago. My changes were not working and I think the reason is a general `github actions` failure that started several days ago: https://www.githubstatus.com/history

Reverting typescript update

---

.bazelrc

Q&A:
- What's the motivation? https://engflow.slack.com/archives/C01CPGQQ87N/p1680695117618029
- Is it fine to remove --host_platform? Yes it is, Bazel detects that automatically. There can be only one host platform anyway, whereas multiple target platforms may be specified.
- Why use a newer version than the others? Because there is no 3.1.100 for this OS/platform.
- Why not update the other versions? Because I don't need to and I'm not sure what it causes.

Bazelrc: fix macos/arm64 toolchain flag

---

WORKSPACE

In order for renovate bot to update only releases/tags instead of commit changes (too much noise)  
Also formatting.

Setting grpc-java and rules_jvm_external to specific versions

---

.github/workflows/renovate.yml

Because every week is too much noise and it is not necessary.

[ci] Run renovate bot each 15 days (roughly)

---

.github/workflows/main.yml
swift/BUILD
typescript/BUILD

- Because it need `--config=clang` too, making `bazel build //...` fail
- Also formatted typescript `BUILD` file.

Tagging swift as manual (because of its clang flag)

---

BUILD
WORKSPACE
deps.bzl
go.mod
go/BUILD
perl/BUILD

This will be needed shortly for a wrapper tool in an upcoming PR.
It's a good example anyway.
- In WORKSPACE, add dependency on bazel_gazelle.
- Add deps.bzl with a go_dependencies macro, tracking dependenices from
this workspace. Empty for now.
- Add go.mod, go.sum tracking Go dependencies. Empty for now.
- Add root BUILD file, declaring a Gazelle target.
- Run gazelle. This cleans up go/BUILD and perl/BUILD.

Upgrade Go, use Gazelle

---

platform/linux_x64/docker/Dockerfile
platform/linux_x64/docker/README.md

And link back to public documentation, when it exists.
For linear/CUS-64

linux_x64: provide example Dockerfile

---

deps.bzl
go.mod
go.sum
infra/msvc_filter_showincludes/BUILD
infra/msvc_filter_showincludes/msvc_filter_showincludes.go
infra/msvc_filter_showincludes/msvc_filter_showincludes_test.go

This is a wrapper around the cl.exe compiler for Windows MSVC toolchains. It works around bazelbuild/bazel#19733 by filtering EngFlow execroot directories out of MSVC's /showincludes output so Bazel does not see them. The package documentation explains this is more detail.
For linear/PE-1127, linear/CUS-81, linear/CUS-64, linear/PE-1434

Add infra/msvc_filter_showincludes

---

.bazelrc
infra/test-all.py

Not really sure why, but specifying JWT authentication flags multiple times
causes Bazel to crash with no output, exit code 37.
Remove the redundant --config=opal_auth from the opal_bes and magnesite_bes
configurations. Add to test-all.py when remote execution is disabled.
I think we don't see this in CI because credential helper flags are safe
to specify more than once but --remote_header is not.
For linear/PE-2268

.bazelrc: fix redundancy that caused a Bazel crash

---

.vscode/settings.json
WORKSPACE
go/main.go
infra/gopackagesdriver.sh

Following instructions at
https://github.com/bazelbuild/rules_go/wiki/Editor-setuphttps://github.com/bazelbuild/rules_go/wiki/Editor-setup

go: upgrade Go, rules_go, and enable VSCode Go editor support

---

WORKSPACE

If no go_download_sdk is declared, go_register_toolchains
automatically declares one for the host platform. But it fails
toolchains resolution if the execution platform is different
than the host platform.

go: support remote cross-compilation

---

platform/windows_x64/docker/normalize_os_windows.ps1

- Towards CUS-227
- Added script according to the [ticket description](https://linear.app/engflow/issue/CUS-227/windows-ci-cant-create-symbolic-links-in-docker-actions) 
- Built the docker image in `gcp` windows dev machine
- Logged into docker aws and pushed the image (see [glass](https://eu-west-1.console.aws.amazon.com/ecr/repositories/private/645088952840/engflow-re/windows-x64?region=eu-west-1))

[windows] Enabling dev mode in docker

---

MODULE.bazel
MODULE.bazel.lock

As @jayconrod noted in EngFlow/engflow#21551, in rules_go 0.47.1:
> ...the go_sdk extension automatically instantiates go_download_sdk
> repositories for common remote platforms...
Hence the removal of GO_PLATFORMS and the individual go_sdk.download() calls. These are replaced by a single go_sdk.download() call that sets the Go version per:
- https://github.com/bazelbuild/rules_go/blob/master/docs/go/core/bzlmod.md#go-sdks

Bump to rules_go 0.47.1, Go 1.22.3

---

MODULE.bazel
MODULE.bazel.lock
README.md

Also removes extra whitespace and blank lines from README.md.
I inadvertently broke Swift builds and tests in #317 because I added a `bazel_dep()` for `rules_cc` _before_ the one for `apple_support`. This restores the proper order.
FWIW, building or testing `//swift:tests` remotely still doesn't seem to work. It hangs on `--config=remote_macos_x64`, and fails on `--config=remote_linux_x64` with:
```txt
ERROR: .../external/rules_swift~~non_module_deps~build_bazel_rules_swift_local_config/BUILD:9:22:
in xcode_swift_toolchain rule
@@rules_swift~~non_module_deps~build_bazel_rules_swift_local_config//:toolchain:
Traceback (most recent call last):
File ".../external/rules_swift~/swift/internal/xcode_swift_toolchain.bzl",
line 641, column 21, in _xcode_swift_toolchain_impl
env = …
```

Fix `bazel test //swift:tests` via Bzlmod ordering

---

runfiles/README.md

The blog post "Migrating to Bazel Modules (a.k.a. Bzlmod) - Repo Names and Runfiles" is now live:
- https://blog.engflow.com/2024/08/09/migrating-to-bazel-modules-aka-bzlmod---repo-names-and-runfiles/

Add link to blog post from runfiles/README.md

---

.bazelrc
.github/workflows/main.yml

https://linear.app/engflow/issue/AX-591/migrate-debian-11-jobs-to-ci-runners
Prerequisite: https://github.com/EngFlow/prod/pull/13635

Migrating to CI Runners AX-591

---

bzlmod/canonical-repo-name-injection/README.md

The blog post "Migrating to Bazel Modules (a.k.a. Bzlmod) - Repo Names, Macros, and Variables" is now live:
- https://blog.engflow.com/2024/09/06/migrating-to-bazel-modules-aka-bzlmod---repo-names-macros-and-variables/

Add link to blog post from canonical names README

---

MODULE.bazel
MODULE.bazel.lock
scala/extensions/config.bzl

This updates //scala/extensions:config.bzl to provide a proper module API that allows the user to configure different Scala versions.
For now, 2.13.12 is the latest Scala 2 version supported by rules_scala (v6.6.0), defined in //third_party/repositories:scala_2_13.bzl. Setting it to a later version results in an error:
```txt
File "@io_bazel_rules_scala//third_party/repositories/repositories.bzl",
line 86, column 17, in repositories
fail(version_message % (scala_version, repository_scala_version))
Error in fail:
Scala config (2.13.14) version does not match repository version (2.13.12)
```

Enable different Scala versions

---

.bazelrc
MODULE.bazel.lock

This sets `--java_runtime_version` and `--java_language_version` to fix remote execution builds that otherwise fail with the error:
```txt
$ bazel build --config=engflow //java/...
ERROR: .../java/com/engflow/notificationqueue/BUILD:37:12:
While resolving toolchains for target
//java/com/engflow/notificationqueue:client (e53c356):
No matching toolchains found for types
@@bazel_tools//tools/jdk:runtime_toolchain_type.
ERROR: Analysis of target '//java/com/engflow/notificationqueue:client'
failed; build aborted
```
This affects the other `rules_java`/JVM based targets under `//kotlin` and `//scala` as well. Local builds continue to pass.

Set Java version to fix remote execution builds

---

java/com/engflow/notificationqueue/Client.java
java/com/engflow/notificationqueue/README.md

NQ example: fix token usage in code & docs
